encyclopedia/urls.py
from os import name
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>",views.load_page,name="load_page"),
    path("search/",views.search, name="search"),
    path("create/",views.create,name="create"),
    path("edit/<str:title>",views.edit,name="edit"),
    path("random/",views.randomPick,name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from turtle import title
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
import markdown2
from django.urls import reverse
from . import util
import random




def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })



def load_page(request,title):
    content = util.get_entry(title)
    if content:
        content_html = markdown2.markdown(content)
        return render(request,"encyclopedia/markupContent.html",{
            "content":content_html,
            "title":title
        })
    else:
        return render(request,"encyclopedia/error_404.html",{
            "error_message":"Page Does Not Exist"
        })



def search(request):
    entry = request.GET.get("q")
    content = util.get_entry(entry)
    if content:
        return HttpResponseRedirect(reverse("encyclopedia:load_page",args=(entry,)))
    entries = util.list_entries()
    matched = list()
    for ent in entries:
        if entry.lower() in ent.lower():
            matched.append(ent)
    return render(request,"encyclopedia/substring_results.html",{
        "matched":matched
    })



def create(request):
    if request.method == "POST":
        title = request.POST.get("title")
        content=request.POST.get("content")
        if title and content:
            check = util.get_entry(title)
            if check:
                util.save_entry(title,content)
                return render(request,"encyclopedia/error_404.html",{
                    "error_message":"Entry With Title Already Exist, old entry replaced"
                })
            util.save_entry(title,content)
            return HttpResponseRedirect(reverse("encyclopedia:load_page",args=(title,)))
      
        return HttpResponse("error")
    return render(request,"encyclopedia/newpage.html")



def edit(request,title):
    if request.method == "POST":
        try:
            util.save_entry(title,request.POST.get("content"))
            return HttpResponseRedirect(reverse("encyclopedia:load_page",args=(title,)))
        except Exception as e:
             return render(request,"encyclopedia/error_404.html",{
                    "error_message":e})

    content = util.get_entry(title)
    return render(request,"encyclopedia/editpage.html",{
        "content":content
    })



def randomPick(request):
    entries = util.list_entries()
    if entries:
        lucky_21 = random.choice(entries)
        return HttpResponseRedirect(reverse("encyclopedia:load_page",args=(lucky_21,)))

    return render(request,"encyclopedia/error_404.html",{
                    "error_message":"Thew are no current entries at the moment"})

encyclopedia/templates/encyclopedia/editpage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
edit
{% endblock title %}

{% block body %}
<form method="post" >
    {% csrf_token %}
    <p><input class="btn btn-success" type="submit" value="save"></p>
    <textarea name="content" id="" cols="30" rows="10" >{{content}}</textarea>
</form>
{% endblock body %}

encyclopedia/templates/encyclopedia/error_404.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
error
{% endblock title %}

{% block body %}  
<h1 class ="text-center text-danger mt-5">ERROR: {{error_message}}</h1>
{% endblock body %} 

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href = "{% url 'encyclopedia:load_page' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action = "{% url 'encyclopedia:search'%}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href= "{% url 'encyclopedia:create'%}">Create New Page</a>
                </div>
                <div>
                   <a href= "{% url 'encyclopedia:random' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/markupContent.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}
{{title}}
{% endblock title %}

{% block body %}
{{content|safe}}

<a href= "{%url 'encyclopedia:edit' title %}">Edit</a>
{% endblock body %}

encyclopedia/templates/encyclopedia/newpage.html
{% extends 'encyclopedia/layout.html' %}
{% block title %}
new page
{% endblock title %}

{% block body %}
<form method="post">
    {% csrf_token %}
    <div class="row">
        <div class="col">
           <p><label class="fs-3" for="title">TITLE</label></p> 
            <input type="text" name="title" id="title">
        </div>
        <div class="col">
            <input class="btn btn-success" type="submit" value="SAVE">
        </div>
    </div>
    
    <div>
        <p class="mt-2"><label for="content">Page Content</label></p>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>
</form>


{% endblock body %}

encyclopedia/templates/encyclopedia/substring_results.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}
results
{% endblock title %}

{% block body %}
{%for match in matched%}
<li><a href = "{% url 'encyclopedia:load_page' match %}">{{match}}</a></li>
{% endfor %}
{% endblock body %}